# Use custom format:
format = '''
$directory$git_branch$git_status$c$cmake$lua$python$rust$golang$java$nodejs$conda$docker_context$container$package
$character
'''

# Prompt symbols
[character]
success_symbol = "[ó°‰](#9ece6a bold)"
error_symbol = "[ï€](#db4b4b)"
vicmd_symbol = "[î˜«](#9ece6a)"
vimcmd_replace_one_symbol = "[î˜«](#d19a66)"
vimcmd_replace_symbol = "[î˜«](#e0af6e)"
vimcmd_visual_symbol = "[î˜«](#c678dd)"

[os]
format = "[î‚¶]($style)[$symbol](bg:#292E42 fg:#7aa2f7)"
# style = "bg:#292E42 fg:#7aa2f7"
style = "#292E42"

[os.symbols]
Windows = "î˜ª "
Macos = "ï…¹ "
FreeBSD = "ïŒŒ "
Android = "ó°€² "
Alpine = "ó°Š  "
Amazon = "ó°Š  "
Arch = "ó°Š  "
CentOS = "ó°Š  "
Debian = "ó°Š  "
DragonFly = "ó°Š  "
Emscripten = "ó°Š  "
EndeavourOS = "ó°Š  "
Fedora = "ó°Š  "
Garuda = "ó°Š  "
Gentoo = "ó°Š  "
HardenedBSD = "ó°Š  "
Illumos = "ó°Š  "
Linux = "ó°Š  "
Manjaro = "ó°Š  "
Mariner = "ó°Š  "
MidnightBSD = "ó°Š  "
Mint = "ó°Š  "
NetBSD = "ó°Š  "
NixOS = "ó°Š  "
OpenBSD = "ó°Š  "
OpenCloudOS = "ó°Š  "
openEuler = "ó°Š  "
openSUSE = "ó°Š  "
OracleLinux = "ó°Š  "
Pop = "ó°Š  "
Raspbian = "ó°Š  "
Redhat = "ó°Š  "
RedHatEnterprise = "ó°Š  "
Redox = "ó°Š  "
Solus = "ó°Š  "
SUSE = "ó°Š  "
Ubuntu = "ó°Š  "
Unknown = "ï„¨ "

[directory]
read_only = " ó°Œ¾ "
read_only_style = "bg:#292E42 fg:#db4b4b"
format = "[î‚¶]($style)[ó°Š  ](bg:#292E42 fg:#7aa2f7)[[$path](bg:#292E42 fg:#a9b1d6)](bg:#292E42 fg:#c0caf5)[$read_only]($read_only_style)[î‚´ ]($style)"
style = "#292E42"

[git_branch]
symbol = "ï˜ "
format = "[î‚¶]($style)[[$symbol](bg:#292E42 fg:#9ece6a)[$branch](bg:#292E42 fg:#a9b1d6)](bg:#292E42 fg:#c0caf5)"
style = "#292E42"

[git_status]
format = "[ $all_status$ahead_behind]($style)[î‚´ ](#292E42)"
style = "bg:#292E42 fg:#db4b4b"
conflicted = "ï€¤ "
up_to_date = "ï€Œ "
untracked = "ó°·Œ "
modified = "î« "
renamed = "î«  "
deleted = "ï‘˜ "
staged = "ï‘— "
ahead = "ó°œ·"
diverged = "ó°¹º"
behind = "ó°œ®"
stashed = "ï€œ "

[battery]
full_symbol = "ó°¹"
charging_symbol = "ó°‚„"
discharging_symbol = "ó°‚ƒ"

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’"

[c]
symbol = "î˜ "
format = "[î‚¶]($style)[$symbol($version(-$name))](bg:#292e42 fg:#4abaaf)[î‚´ ]($style)"
style = "#292E42"

[cmake]
symbol = "ó°”¶ "
format = "[î‚¶]($style)[$symbol($version)](bg:#292e42 fg:#7aa2f7)[î‚´ ]($style)"
style = "#292E42"

[conda]
symbol = "ï„Œ "
format = "[î‚¶]($style)[$symbol$environment](bg:#292e42 fg:#98c379)[î‚´ ]($style)"
style = "#292E42"

[container]
format = "[î‚¶]($style)[$symbol$name](bg:#292e42 fg:#9a7ecc)[î‚´ ]($style)"
style = "#292E42"

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "
format = "[î‚¶]($style)[$symbol$context](bg:#292e42 fg:#61afef)[î‚´ ]($style)"
style = "#292E42"

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[golang]
symbol = "î˜§ "
format = "[î‚¶]($style)[$symbol$version](bg:#292e42 fg:#56b6c2)[î‚´ ]($style)"
style = "#292E42"

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "
format = "[î‚¶]($style)[$symbol$version](bg:#292e42 fg:#abb2bf)[î‚´ ]($style)"
style = "#292E42"

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "
format = "[î‚¶]($style)[$symbol$version](bg:#292e42 fg:#61afef)[î‚´ ]($style)"
style = "#292E42"

[memory_usage]
symbol = "ï¡š "

[meson]
symbol = "ï¨¶"

[nim]
symbol = "î™·"

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "
format = "[î‚¶]($style)[$symbol$version](bg:#292e42 fg:#98c379)[î‚´ ]($style)"
style = "#292E42"

[package]
symbol = "ï£– "
format = "[î‚¶]($style)[$symbol$version](bg:#292e42 fg:#9a7ecc)[î‚´ ]($style)"
style = "#292E42"

[python]
symbol = "îˆµ "
format = "[î‚¶]($style)[${symbol}${pyenv_prefix}${version}$virtualenv](bg:#292e42 fg:#e0af68)[î‚´ ]($style)"
style = "#292E42"

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "ó±˜— "
format = "[î‚¶]($style)[$symbol$version](bg:#292e42 fg:#e06c75)[î‚´ ]($style)"
style = "#292E42"

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "
