# Use custom format:
format='''
$os$directory$git_branch$git_status
$character
'''

# Prompt symbols 
[character]
success_symbol = "[ï€](#9ece6a bold)"
error_symbol = "[ï€](#db4b4b)"
vicmd_symbol = "[î˜«](#9ece6a)"
vimcmd_replace_one_symbol = "[î˜«](#d19a66)"
vimcmd_replace_symbol = "[î˜«](#e0af6e)"
vimcmd_visual_symbol = "[î˜«](#c678dd)"

[os]
format = "[î‚¶]($style)[$symbol](bg:#292E42 fg:#7aa2f7)"
# style = "bg:#292E42 fg:#7aa2f7"
style = "bg:#1a1b26 fg:#292E42"
disabled = false

[os.symbols]
Windows = "î˜ª "
Macos = "ï…¹ "
FreeBSD = "ïŒŒ "
Android = "ó°€² "
Alpine = "ïŸ "
Amazon = "ïŸ "
Arch = "ïŸ "
CentOS = "ïŸ "
Debian = "ïŸ "
DragonFly = "ïŸ "
Emscripten = "ïŸ "
EndeavourOS = "ïŸ "
Fedora = "ïŸ "
Garuda = "ïŸ "
Gentoo = "ïŸ "
HardenedBSD = "ïŸ "
Illumos = "ïŸ "
Linux = "ïŸ "
Manjaro = "ïŸ "
Mariner = "ïŸ "
MidnightBSD = "ïŸ "
Mint = "ïŸ "
NetBSD = "ïŸ "
NixOS = "ïŸ "
OpenBSD = "ïŸ "
OpenCloudOS = "ïŸ "
openEuler = "ïŸ "
openSUSE = "ïŸ "
OracleLinux = "ïŸ "
Pop = "ïŸ "
Raspbian = "ïŸ "
Redhat = "ïŸ "
RedHatEnterprise = "ïŸ "
Redox = "ïŸ "
Solus = "ïŸ "
SUSE = "ïŸ "
Ubuntu = "ïŸ "
Unknown = "ï„¨ "

[directory]
read_only = " ï ½ "
read_only_style = "bg:#292E42 fg:#db4b4b"
format = "[[$path](bg:#292E42 fg:#a9b1d6)](bg:#292E42 fg:#c0caf5)[$read_only]($read_only_style)[î‚´ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[git_branch]
symbol = "ï˜ "
format = "[î‚¶]($style)[[$symbol](bg:#292E42 fg:#9ece6a)[$branch](bg:#292E42 fg:#a9b1d6)](bg:#292E42 fg:#c0caf5)"
style = "bg:#1a1b26 fg:#292E42"

[git_status]
format = "[ $all_status$ahead_behind]($style)[î‚´](bg:#1a1b26 fg:#292E42)"
style = "bg:#292E42 fg:#db4b4b"

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ï¡š "

[meson]
symbol = "ï¨¶ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "
